### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by ojotoxy** [kevinGodell/pipe2jpeg#1]
How is the protocol parsed into full JPEG files?

**Comment by kevinGodell** [comment]
It just simply looks for the SOI (start of image) and EOI (end of image) of the jpeg and splices it out of the buffer that is piped from ffmpeg. Depending on the size of the jpeg and the size of the pipe, ffmpeg may not pipe the jpeg in one complete chunk. We have to hold on to its pieces until it is complete and then pipe it or emit a jpeg event containing the jpeg data as a buffer.

**Comment by ojotoxy** [comment]
Thanks

Just wondering, is there a definitive answer somewhere as to whether the EOI tag can appear somewhere in the middle of a JPEG?

**Comment by kevinGodell** [comment]
I think the specs say that there may be a thumbnail embedded inside of the jpeg, but while working with grabbing jpegs from ffmpeg, I never ran into any situation where there was more than one EOI for a single image. If you clone this project and run `npm test` it always passes for me and extracts the expected number of jpegs. `test2.js` is the file that tells ffmpeg to output jpegs at a very high frame rate and small size causing multiple jpegs to be packed together in same buffer.

**Comment by kmxz** [comment]
I'm curious about this as well, as `FFD8` (SOI) and `FFD9` (EOI) may be found before the end of a JPEG file.

The standard does prevent the existance of them in the entropy-encoded data blocks, as described in [ISO/IEC 10918-1:1993](https://www.w3.org/Graphics/JPEG/itu-t81.pdf) _B.1.1.5 Note 2_. But for the header blocks, there's no such guarantee. 

I believe https://stackoverflow.com/a/1602428 describes a more robust way to find JPEG file borders. The current implementation of this module is not fully correct.

Luckily, for the case of ffmpeg output, there won't be thumbnails, and it's highly unlikely for 0xFFD8 and 0xFFD9 to appear in header blocks, so this module should have no problem in most of the cases.
